version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 barua.wsgi:application
    volumes:
      - .:/barua
    expose:
      - 8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - .:/barua
    ports:
      - "85:85"
    depends_on:
      - web

volumes:
  postgres_data:
